[package]
name = "lupercal"
licence = "MIT"
authors = ["Bethany Davis <ellis@despoena.com>"]
description = "A single binary console based Gemini Protocol server and client."
repository = "https://github.com/countessellis/lupercal"
homepage = "https://github.com/countessellis/lupercal"
readme = "README.md"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lupercal"
path = "src/main.rs"

[lib]
name = "lupercal"
path = "src/lib.rs"

[dependencies]
ansi_term = "0.12.1"
env_logger = "0.11.8"
tiny_http = { version = "0.12.0", features = ["ssl-openssl"] }
log = "0.4.29"
openssl = { version = "0.10", features = ["vendored"] }
base64 = "0.22.1"
url = "2.5.7"
mime_guess = "2.0.5"
rpassword = "7.4.0"
color-eyre = "0.6.5"
ratatui = "0.30.0"
textwrap = "0.16.2"
tui-logger = { version = "0.18.0", features = ["tracing", "tracing-subscriber", "tracing-support"] }
gag = "1.0.0"
dirs = "6.0.0"
shellexpand = "3.1.1"
fs_extra = "1.3.0"
infer = "0.19.0"
walkdir = "2.5.0"
tracing = "0.1.44"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.22"
is-terminal = "0.4.17"

[build-dependencies]
chrono = "0.4.42"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

