[package]
name = "lupercal"
license = "MIT"
authors = ["Bethany Davis <ellis@despoena.com>"]
description = "A single binary console based Gemini Protocol server and client."
repository = "https://github.com/countessellis/lupercal"
homepage = "https://github.com/countessellis/lupercal"
readme = "README.md"
version = "1.0.0"
edition = "2024"
default-run = "lupercal"

[[bin]]
name = "lupercal"
path = "src/main.rs"

[[bin]]
name = "lupercal-server"
path = "src/bin/server.rs"

[[bin]]
name = "lupercal-client"
path = "src/bin/client.rs"

[[bin]]
name = "lupercal-proxy"
path = "src/bin/proxy.rs"

[[bin]]
name = "lupercal-convert"
path = "src/bin/convert.rs"

[lib]
name = "lupercal"
path = "src/lib.rs"

[dependencies]
ansi_term = "0.12.1"
env_logger = "0.11.8"
log = "0.4.29"
openssl = { version = "0.10", features = ["vendored"] }
url = "2.5.7"
mime_guess = "2.0.5"
rpassword = "7.4.0"
ratatui = "0.30.0"
textwrap = "0.16.2"
tui-logger = { version = "0.18.0", features = ["tracing", "tracing-subscriber", "tracing-support"] }
gag = "1.0.0"
dirs = "6.0.0"
walkdir = "2.5.0"
tracing-subscriber = { version = "0.3.22", features = ["time"] }
is-terminal = "0.4.17"
hex = "0.4.3"
time = { version = "0.3.45", features = ["formatting", "macros", "parsing"] }
strip-prefix-suffix-sane = "0.1.0"
tracing-log = "0.2.0"
tracing-journald = "0.3.2"
tracing-appender = "0.2.4"

[build-dependencies]
chrono = "0.4.42"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin-gcc"

[package.metadata.rpm]
package = "lupercal"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
"./src/bin/client" = { path = "/usr/bin/./src/bin/client" }
"./src/bin/convert" = { path = "/usr/bin/./src/bin/convert" }
"./src/bin/server" = { path = "/usr/bin/./src/bin/server" }
"./src/bin/proxy" = { path = "/usr/bin/./src/bin/proxy" }
