[package]
name = "lupercal"
license = "MIT"
authors = ["Bethany Davis <ellis@despoena.com>"]
description = "A single binary console based Gemini Protocol server and client."
repository = "https://github.com/countessellis/lupercal"
version = "1.0.1"
edition = "2024"
default-run = "lupercal"

[[bin]]
name = "lupercal"
path = "src/main.rs"

[[bin]]
name = "lupercal-server"
path = "src/bin/server.rs"

[[bin]]
name = "lupercal-client"
path = "src/bin/client.rs"

[[bin]]
name = "lupercal-proxy"
path = "src/bin/proxy.rs"

[[bin]]
name = "lupercal-convert"
path = "src/bin/convert.rs"

[lib]
name = "lupercal"
path = "src/lib.rs"

[dependencies]
dirs = "7.0"
env_logger = "0.11"
gag = "1.0"
hex = "0.4"
is-terminal = "0.4"
log = "0.4"
mime_guess = "2.0"
nu-ansi-term = "0.50"
openssl = { version = "0.10", features = ["vendored"] }
ratatui = "0.30"
rpassword = "7.4"
strip-prefix-suffix-sane = "0.1"
textwrap = "0.16"
time = { version = "0.3", features = ["formatting", "macros", "parsing"] }
tracing-log = "0.2"
tracing-appender = "0.2"
tracing-journald = "0.3"
tracing-subscriber = { version = "0.3", features = ["time"] }
tui-logger = { version = "0.18", features = ["tracing", "tracing-subscriber", "tracing-support"] }
url = "2.5"
walkdir = "2.5"

[build-dependencies]
chrono = "0.4"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.deb]
assets = [
  { source = "target/release/lupercal", dest = "/usr/bin/lupercal", mode = "755" },
  { source = "target/release/lupercal-client", dest = "/usr/bin/lupercal-client", mode = "755" },
  { source = "target/release/lupercal-server", dest = "/usr/bin/lupercal-server", mode = "755" },
  { source = "target/release/lupercal-proxy", dest = "/usr/bin/lupercal-proxy", mode = "755" },
  { source = "target/release/lupercal-convert", dest = "/usr/bin/lupercal-convert", mode = "755" },
  { source = "content/**/*", dest = "/usr/share/lupercal/content", mode = "644" }
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin-gcc"

[package.metadata.rpm]
package = "lupercal"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
"./src/bin/client" = { path = "/usr/bin/./src/bin/client" }
"./src/bin/convert" = { path = "/usr/bin/./src/bin/convert" }
"./src/bin/server" = { path = "/usr/bin/./src/bin/server" }
"./src/bin/proxy" = { path = "/usr/bin/./src/bin/proxy" }

[package.metadata.generate-rpm]
assets = [
  { source = "target/release/lupercal", dest = "/usr/bin/lupercal", mode = "755" },
  { source = "target/release/lupercal-client", dest = "/usr/bin/lupercal-client", mode = "755" },
  { source = "target/release/lupercal-server", dest = "/usr/bin/lupercal-server", mode = "755" },
  { source = "target/release/lupercal-proxy", dest = "/usr/bin/lupercal-proxy", mode = "755" },
  { source = "target/release/lupercal-convert", dest = "/usr/bin/lupercal-convert", mode = "755" },
  { source = "content/**/*", dest = "/usr/share/lupercal/content", mode = "644" }
]
