[build.env]
passthrough = [
    "OPENSSL_VENDORED",
    "OPENSSL_STATIC",
    "PKG_CONFIG_ALLOW_CROSS",
    "CC_aarch64_unknown_linux_gnu",
    "AR_aarch64_unknown_linux_gnu",
    "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER"
]
